server:
  port: 8080

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create

  datasource:
    password: 232323
    driver-class-name: org.mariadb.jdbc.Driver
    username: resumeuser
    url: jdbc:mariadb://resume-mysql:3306/resume?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

  sql:
    init:
      mode: always