server:
  port: 8080

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create

  datasource:
    password: shvhsy8571@
    driver-class-name: org.mariadb.jdbc.Driver
    username: hyeon8900
    url: jdbc:mariadb://localhost:3306/resume?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

  sql:
    init:
      mode: always